services:
  tunnel:
    #network_mode: "pasta"
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run --protocol http2
    stop_grace_period: 5s
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    #dns:
    #  - 1.1.1.1
  fastdl-tun-but-h2:
    network_mode: "service:tunnel"
    #build: fastdl-tun-but-h2
    image: ghcr.io/srcwr/fastdl-tun-but-h2:latest
    user: 1000:1000
    restart: unless-stopped
    stop_grace_period: 1s
    environment:
      - RUST_LOG=${RUST_LOG}
      - PROCESSED_DIR_INNER=${PROCESSED_DIR_INNER}
      - FORMS_DIR_INNER=${FORMS_DIR_INNER}
      - FORM_POST_PATH=${FORM_POST_PATH}
      - NODE_ID=${NODE_ID}
      - REAL_WORKER_HEADER=${REAL_WORKER_HEADER}
      - REAL_IP_HEADER=${REAL_IP_HEADER}
      - REAL_FORWARDED_PROTO_HEADER=${REAL_FORWARDED_PROTO_HEADER}
      - REAL_COUNTRY_HEADER=${REAL_COUNTRY_HEADER}
      - THIRDPARTY_REDIRECTS=${THIRDPARTY_REDIRECTS}
      - SENSITIVE_HEADERS=${SENSITIVE_HEADERS}
    volumes:
      - ${PROCESSED_DIR_OUTER}:/processed:ro
      - ${FORMS_DIR_OUTER}:/forms
    depends_on:
      - tunnel
