services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run --protocol http2
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ${PROCESSED_DIR}:/data:ro
      - ${LOGS_DIR}:/var/log/nginx
      - ./nginx/fastdl.me-3rdparty-shared.conf:/etc/nginx/fastdl.me-3rdparty-shared.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy_params.conf:/etc/nginx/proxy_params.conf:ro
      - ./nginx/secret-headers.conf:/etc/nginx/secret-headers.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
  fastdlpy:
    build: fastdlpy
    restart: unless-stopped
    stop_grace_period: 2s
    volumes:
      - ${PROCESSED_DIR}:/data:ro
