[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.x86_64-unknown-linux-gnu]
rustflags = [
	"-Ctarget-cpu=native",
	"-Clink-arg=-fuse-ld=mold",
	"-Clinker=clang++",
]
